Upgrade: Bump view_component from 3.0.0 to 3.1.0 (#3832)
Bumps [view_component](https://github.com/viewcomponent/view_component)
from 3.0.0 to 3.1.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/viewcomponent/view_component/releases">view_component's
releases</a>.</em></p>
<blockquote>
<h2>v3.1.0</h2>
<ul>
<li>
<p>Check <code>defined?(Rails) &amp;&amp; Rails.application</code>
before using
<code>ViewComponent::Base.config.view_component_path</code>.</p>
<p><em>Donapieppo</em></p>
</li>
<li>
<p>Allow customization of polymorphic slot setters.</p>
<p><em>Cameron Dutro</em></p>
</li>
<li>
<p>Fix duplication in configuration docs.</p>
<p><em>Tom Chen</em></p>
</li>
<li>
<p>Fix helpers not reloading in development.</p>
<p><em>Jonathan del Strother</em></p>
</li>
<li>
<p>Add <code>SECURITY.md</code>.</p>
<p><em>Joel Hawksley</em></p>
</li>
<li>
<p>Add Ophelos to list of companies using ViewComponent.</p>
<p><em>Graham Rogers</em></p>
</li>
<li>
<p>Add FlightLogger to list of companies using ViewComponent.</p>
<p><em>Joseph Carpenter</em></p>
</li>
<li>
<p>Fix coverage reports overwriting each other when running locally.</p>
<p><em>Jonathan del Strother</em></p>
</li>
<li>
<p>Add <a
href="https://github.com/reeganviljoen"><code>@​reeganviljoen</code></a>
to triage team.</p>
<p><em>Reegan Viljoen</em></p>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/ViewComponent/view_component/blob/main/docs/CHANGELOG.md">view_component's
changelog</a>.</em></p>
<blockquote>
<h2>3.1.0</h2>
<ul>
<li>
<p>Check <code>defined?(Rails) &amp;&amp; Rails.application</code>
before using
<code>ViewComponent::Base.config.view_component_path</code>.</p>
<p><em>Donapieppo</em></p>
</li>
<li>
<p>Allow customization of polymorphic slot setters.</p>
<p><em>Cameron Dutro</em></p>
</li>
<li>
<p>Fix duplication in configuration docs.</p>
<p><em>Tom Chen</em></p>
</li>
<li>
<p>Fix helpers not reloading in development.</p>
<p><em>Jonathan del Strother</em></p>
</li>
<li>
<p>Add <code>SECURITY.md</code>.</p>
<p><em>Joel Hawksley</em></p>
</li>
<li>
<p>Add Ophelos to list of companies using ViewComponent.</p>
<p><em>Graham Rogers</em></p>
</li>
<li>
<p>Add FlightLogger to list of companies using ViewComponent.</p>
<p><em>Joseph Carpenter</em></p>
</li>
<li>
<p>Fix coverage reports overwriting each other when running locally.</p>
<p><em>Jonathan del Strother</em></p>
</li>
<li>
<p>Add <a
href="https://github.com/reeganviljoen"><code>@​reeganviljoen</code></a>
to triage team.</p>
<p><em>Reegan Viljoen</em></p>
</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/ViewComponent/view_component/commit/904c4803a9837a4f9559bc90adf1fb44c33fd411"><code>904c480</code></a>
release 3.1.0 (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1762">#1762</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/35cc67d75a4ef2b35054f7a95b998f6441fe7450"><code>35cc67d</code></a>
Request to Join traige Team (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1761">#1761</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/f949135b77ae0df140ed49e74ccbb06ca922e22e"><code>f949135</code></a>
Bump debug from 1.7.2 to 1.8.0 (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1759">#1759</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/7349ae2f9cc10879670726dd00fd32695c4eb73a"><code>7349ae2</code></a>
Bump rails from 7.0.4.3 to 7.0.5 (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1757">#1757</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/b9bac8e86d3e5d8709e0398e119c957382076b3f"><code>b9bac8e</code></a>
Bump standard from 1.28.2 to 1.28.4 (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1758">#1758</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/f7d26fa930bd99fc6aedf3aa170f639dd3e2a824"><code>f7d26fa</code></a>
TypeError: no implicit conversion of nil into String (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1738">#1738</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/f73bc31723c7e932dbd46864a953e973a6de333e"><code>f73bc31</code></a>
Allow customization of polymorphic slot setters (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1740">#1740</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/3b3a37f2b54eeeb58611946f6c281ca187b51c89"><code>3b3a37f</code></a>
Make it easier to run coverage reports locally (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1750">#1750</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/649a5bd6c009cbdbe31b4113f9dca2dec68d76f6"><code>649a5bd</code></a>
Bump slim from 5.1.0 to 5.1.1 (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1754">#1754</a>)</li>
<li><a
href="https://github.com/ViewComponent/view_component/commit/390f35adc97a62a60a46463cbd654ed7c416ddfc"><code>390f35a</code></a>
Fix duplication in configuration docs (<a
href="https://redirect.github.com/viewcomponent/view_component/issues/1752">#1752</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/viewcomponent/view_component/compare/v3.0.0...v3.1.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=view_component&package-manager=bundler&previous-version=3.0.0&new-version=3.1.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>